services:
  api:
    build: .
    container_name: task_manager_api
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${LOCAL_DATABASE_URL}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17-alpine
    container_name: task_manager_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - NEON_DATABASE_URL=${NEON_CLOUD_URL}
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  local_postgres_data: